// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn5AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn16AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
	}
	rn31AllowedHeaders = map[string]string{
		"POST": "X-Api-Key",
	}
	rn6AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn18AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn8AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn20AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn9AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn22AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
	}
	rn34AllowedHeaders = map[string]string{
		"PATCH": "Content-Type,X-Api-Key",
	}
	rn10AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn24AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn11AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn26AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn12AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn2AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Content-Type,X-Api-Key",
	}
	rn13AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn28AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
		"PATCH":  "Content-Type,X-Api-Key",
	}
	rn14AllowedHeaders = map[string]string{
		"GET":  "X-Api-Key",
		"POST": "Content-Type,X-Api-Key",
	}
	rn30AllowedHeaders = map[string]string{
		"DELETE": "X-Api-Key",
		"GET":    "X-Api-Key",
	}
	rn35AllowedHeaders = map[string]string{
		"PATCH": "Content-Type,X-Api-Key",
	}
	rn33AllowedHeaders = map[string]string{
		"GET": "X-Api-Key",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v2/"

			if l := len("/v2/"); len(elem) >= l && elem[0:l] == "/v2/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'c': // Prefix: "conversations"

				if l := len("conversations"); len(elem) >= l && elem[0:l] == "conversations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListConversationsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateConversationRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn5AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "conversation_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteConversationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetConversationRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET",
								allowedHeaders: rn16AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/end"

						if l := len("/end"); len(elem) >= l && elem[0:l] == "/end" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleEndConversationRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn31AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'd': // Prefix: "d"

				if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "eployments"

					if l := len("eployments"); len(elem) >= l && elem[0:l] == "eployments" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListDeploymentsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateDeploymentRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn6AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "deployment_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleDeleteDeploymentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetDeploymentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handleUpdateDeploymentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PATCH",
									allowedHeaders: rn18AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				case 'o': // Prefix: "ocuments"

					if l := len("ocuments"); len(elem) >= l && elem[0:l] == "ocuments" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListDocumentsRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateDocumentRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn8AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "document_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleDeleteDocumentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetDocumentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handleUpdateDocumentRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PATCH",
									allowedHeaders: rn20AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				}

			case 'f': // Prefix: "faces"

				if l := len("faces"); len(elem) >= l && elem[0:l] == "faces" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListFacesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateFaceRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn9AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "face_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteFaceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetFaceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET",
								allowedHeaders: rn22AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/name"

						if l := len("/name"); len(elem) >= l && elem[0:l] == "/name" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "PATCH":
								s.handleRenameFaceRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "PATCH",
									allowedHeaders: rn34AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				}

			case 'g': // Prefix: "guardrails"

				if l := len("guardrails"); len(elem) >= l && elem[0:l] == "guardrails" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListGuardrailsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateGuardrailRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn10AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "guardrail_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteGuardrailRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetGuardrailRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateGuardrailRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PATCH",
								allowedHeaders: rn24AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}

				}

			case 'o': // Prefix: "objectives"

				if l := len("objectives"); len(elem) >= l && elem[0:l] == "objectives" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListObjectivesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateObjectivesRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn11AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "objectives_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteObjectivesRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetObjectivesRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateObjectivesRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PATCH",
								allowedHeaders: rn26AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}

				}

			case 'p': // Prefix: "pals"

				if l := len("pals"); len(elem) >= l && elem[0:l] == "pals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListPalsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreatePalRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn12AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "pal_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeletePalRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetPalRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdatePalRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PATCH",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/tools"

						if l := len("/tools"); len(elem) >= l && elem[0:l] == "/tools" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleAttachToolToPalRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn3AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 't': // Prefix: "tools"

				if l := len("tools"); len(elem) >= l && elem[0:l] == "tools" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListToolsRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateToolRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn13AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "tool_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleDeleteToolRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetToolRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleUpdateToolRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET,PATCH",
								allowedHeaders: rn28AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}

				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ideos"

					if l := len("ideos"); len(elem) >= l && elem[0:l] == "ideos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListVideosRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateVideoRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn14AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "video_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleDeleteVideoRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetVideoRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET",
									allowedHeaders: rn30AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/name"

							if l := len("/name"); len(elem) >= l && elem[0:l] == "/name" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PATCH":
									s.handleRenameVideoRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PATCH",
										allowedHeaders: rn35AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						}

					}

				case 'o': // Prefix: "oices"

					if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleListVoicesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn33AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v2/"

			if l := len("/v2/"); len(elem) >= l && elem[0:l] == "/v2/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'c': // Prefix: "conversations"

				if l := len("conversations"); len(elem) >= l && elem[0:l] == "conversations" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListConversationsOperation
						r.summary = "List all conversations"
						r.operationID = "listConversations"
						r.operationGroup = ""
						r.pathPattern = "/v2/conversations"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateConversationOperation
						r.summary = "Create a conversation"
						r.operationID = "createConversation"
						r.operationGroup = ""
						r.pathPattern = "/v2/conversations"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "conversation_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteConversationOperation
							r.summary = "Delete a conversation"
							r.operationID = "deleteConversation"
							r.operationGroup = ""
							r.pathPattern = "/v2/conversations/{conversation_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetConversationOperation
							r.summary = "Get a conversation"
							r.operationID = "getConversation"
							r.operationGroup = ""
							r.pathPattern = "/v2/conversations/{conversation_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/end"

						if l := len("/end"); len(elem) >= l && elem[0:l] == "/end" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = EndConversationOperation
								r.summary = "End a conversation"
								r.operationID = "endConversation"
								r.operationGroup = ""
								r.pathPattern = "/v2/conversations/{conversation_id}/end"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'd': // Prefix: "d"

				if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'e': // Prefix: "eployments"

					if l := len("eployments"); len(elem) >= l && elem[0:l] == "eployments" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListDeploymentsOperation
							r.summary = "List all deployments"
							r.operationID = "listDeployments"
							r.operationGroup = ""
							r.pathPattern = "/v2/deployments"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateDeploymentOperation
							r.summary = "Create a deployment"
							r.operationID = "createDeployment"
							r.operationGroup = ""
							r.pathPattern = "/v2/deployments"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "deployment_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = DeleteDeploymentOperation
								r.summary = "Delete a deployment"
								r.operationID = "deleteDeployment"
								r.operationGroup = ""
								r.pathPattern = "/v2/deployments/{deployment_id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetDeploymentOperation
								r.summary = "Get a deployment"
								r.operationID = "getDeployment"
								r.operationGroup = ""
								r.pathPattern = "/v2/deployments/{deployment_id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = UpdateDeploymentOperation
								r.summary = "Update a deployment"
								r.operationID = "updateDeployment"
								r.operationGroup = ""
								r.pathPattern = "/v2/deployments/{deployment_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'o': // Prefix: "ocuments"

					if l := len("ocuments"); len(elem) >= l && elem[0:l] == "ocuments" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListDocumentsOperation
							r.summary = "List all documents"
							r.operationID = "listDocuments"
							r.operationGroup = ""
							r.pathPattern = "/v2/documents"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateDocumentOperation
							r.summary = "Upload a document"
							r.operationID = "createDocument"
							r.operationGroup = ""
							r.pathPattern = "/v2/documents"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "document_id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = DeleteDocumentOperation
								r.summary = "Delete a document"
								r.operationID = "deleteDocument"
								r.operationGroup = ""
								r.pathPattern = "/v2/documents/{document_id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetDocumentOperation
								r.summary = "Get a document"
								r.operationID = "getDocument"
								r.operationGroup = ""
								r.pathPattern = "/v2/documents/{document_id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = UpdateDocumentOperation
								r.summary = "Update document metadata"
								r.operationID = "updateDocument"
								r.operationGroup = ""
								r.pathPattern = "/v2/documents/{document_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'f': // Prefix: "faces"

				if l := len("faces"); len(elem) >= l && elem[0:l] == "faces" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListFacesOperation
						r.summary = "List all faces"
						r.operationID = "listFaces"
						r.operationGroup = ""
						r.pathPattern = "/v2/faces"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateFaceOperation
						r.summary = "Create a face"
						r.operationID = "createFace"
						r.operationGroup = ""
						r.pathPattern = "/v2/faces"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "face_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteFaceOperation
							r.summary = "Delete a face"
							r.operationID = "deleteFace"
							r.operationGroup = ""
							r.pathPattern = "/v2/faces/{face_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetFaceOperation
							r.summary = "Get a face"
							r.operationID = "getFace"
							r.operationGroup = ""
							r.pathPattern = "/v2/faces/{face_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/name"

						if l := len("/name"); len(elem) >= l && elem[0:l] == "/name" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "PATCH":
								r.name = RenameFaceOperation
								r.summary = "Rename a face"
								r.operationID = "renameFace"
								r.operationGroup = ""
								r.pathPattern = "/v2/faces/{face_id}/name"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'g': // Prefix: "guardrails"

				if l := len("guardrails"); len(elem) >= l && elem[0:l] == "guardrails" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListGuardrailsOperation
						r.summary = "List all guardrails"
						r.operationID = "listGuardrails"
						r.operationGroup = ""
						r.pathPattern = "/v2/guardrails"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateGuardrailOperation
						r.summary = "Create a guardrail"
						r.operationID = "createGuardrail"
						r.operationGroup = ""
						r.pathPattern = "/v2/guardrails"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "guardrail_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteGuardrailOperation
							r.summary = "Delete a guardrail"
							r.operationID = "deleteGuardrail"
							r.operationGroup = ""
							r.pathPattern = "/v2/guardrails/{guardrail_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetGuardrailOperation
							r.summary = "Get a guardrail"
							r.operationID = "getGuardrail"
							r.operationGroup = ""
							r.pathPattern = "/v2/guardrails/{guardrail_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateGuardrailOperation
							r.summary = "Update a guardrail"
							r.operationID = "updateGuardrail"
							r.operationGroup = ""
							r.pathPattern = "/v2/guardrails/{guardrail_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'o': // Prefix: "objectives"

				if l := len("objectives"); len(elem) >= l && elem[0:l] == "objectives" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListObjectivesOperation
						r.summary = "List all objectives"
						r.operationID = "listObjectives"
						r.operationGroup = ""
						r.pathPattern = "/v2/objectives"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateObjectivesOperation
						r.summary = "Create objectives"
						r.operationID = "createObjectives"
						r.operationGroup = ""
						r.pathPattern = "/v2/objectives"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "objectives_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteObjectivesOperation
							r.summary = "Delete objectives"
							r.operationID = "deleteObjectives"
							r.operationGroup = ""
							r.pathPattern = "/v2/objectives/{objectives_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetObjectivesOperation
							r.summary = "Get objectives"
							r.operationID = "getObjectives"
							r.operationGroup = ""
							r.pathPattern = "/v2/objectives/{objectives_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateObjectivesOperation
							r.summary = "Update objectives"
							r.operationID = "updateObjectives"
							r.operationGroup = ""
							r.pathPattern = "/v2/objectives/{objectives_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'p': // Prefix: "pals"

				if l := len("pals"); len(elem) >= l && elem[0:l] == "pals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListPalsOperation
						r.summary = "List all PALs"
						r.operationID = "listPals"
						r.operationGroup = ""
						r.pathPattern = "/v2/pals"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreatePalOperation
						r.summary = "Create a PAL"
						r.operationID = "createPal"
						r.operationGroup = ""
						r.pathPattern = "/v2/pals"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "pal_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeletePalOperation
							r.summary = "Delete a PAL"
							r.operationID = "deletePal"
							r.operationGroup = ""
							r.pathPattern = "/v2/pals/{pal_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetPalOperation
							r.summary = "Get a PAL"
							r.operationID = "getPal"
							r.operationGroup = ""
							r.pathPattern = "/v2/pals/{pal_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdatePalOperation
							r.summary = "Update a PAL"
							r.operationID = "updatePal"
							r.operationGroup = ""
							r.pathPattern = "/v2/pals/{pal_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/tools"

						if l := len("/tools"); len(elem) >= l && elem[0:l] == "/tools" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = AttachToolToPalOperation
								r.summary = "Attach a tool to a PAL"
								r.operationID = "attachToolToPal"
								r.operationGroup = ""
								r.pathPattern = "/v2/pals/{pal_id}/tools"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 't': // Prefix: "tools"

				if l := len("tools"); len(elem) >= l && elem[0:l] == "tools" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListToolsOperation
						r.summary = "List all tools"
						r.operationID = "listTools"
						r.operationGroup = ""
						r.pathPattern = "/v2/tools"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateToolOperation
						r.summary = "Create a tool"
						r.operationID = "createTool"
						r.operationGroup = ""
						r.pathPattern = "/v2/tools"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "tool_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = DeleteToolOperation
							r.summary = "Delete a tool"
							r.operationID = "deleteTool"
							r.operationGroup = ""
							r.pathPattern = "/v2/tools/{tool_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetToolOperation
							r.summary = "Get a tool"
							r.operationID = "getTool"
							r.operationGroup = ""
							r.pathPattern = "/v2/tools/{tool_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = UpdateToolOperation
							r.summary = "Update a tool"
							r.operationID = "updateTool"
							r.operationGroup = ""
							r.pathPattern = "/v2/tools/{tool_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ideos"

					if l := len("ideos"); len(elem) >= l && elem[0:l] == "ideos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListVideosOperation
							r.summary = "List all videos"
							r.operationID = "listVideos"
							r.operationGroup = ""
							r.pathPattern = "/v2/videos"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = CreateVideoOperation
							r.summary = "Generate a video"
							r.operationID = "createVideo"
							r.operationGroup = ""
							r.pathPattern = "/v2/videos"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "video_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = DeleteVideoOperation
								r.summary = "Delete a video"
								r.operationID = "deleteVideo"
								r.operationGroup = ""
								r.pathPattern = "/v2/videos/{video_id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetVideoOperation
								r.summary = "Get a video"
								r.operationID = "getVideo"
								r.operationGroup = ""
								r.pathPattern = "/v2/videos/{video_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/name"

							if l := len("/name"); len(elem) >= l && elem[0:l] == "/name" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PATCH":
									r.name = RenameVideoOperation
									r.summary = "Rename a video"
									r.operationID = "renameVideo"
									r.operationGroup = ""
									r.pathPattern = "/v2/videos/{video_id}/name"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'o': // Prefix: "oices"

					if l := len("oices"); len(elem) >= l && elem[0:l] == "oices" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ListVoicesOperation
							r.summary = "List available voices"
							r.operationID = "listVoices"
							r.operationGroup = ""
							r.pathPattern = "/v2/voices"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
