// Code generated by ogen, DO NOT EDIT.
package api

type AttachToolToPalRes interface {
	attachToolToPalRes()
}

type CreateConversationRes interface {
	createConversationRes()
}

type CreateDeploymentRes interface {
	createDeploymentRes()
}

type CreateDocumentRes interface {
	createDocumentRes()
}

type CreateFaceRes interface {
	createFaceRes()
}

type CreateGuardrailRes interface {
	createGuardrailRes()
}

type CreateObjectivesRes interface {
	createObjectivesRes()
}

type CreatePalRes interface {
	createPalRes()
}

type CreateToolRes interface {
	createToolRes()
}

type CreateVideoRes interface {
	createVideoRes()
}

type DeleteConversationRes interface {
	deleteConversationRes()
}

type DeleteDeploymentRes interface {
	deleteDeploymentRes()
}

type DeleteDocumentRes interface {
	deleteDocumentRes()
}

type DeleteFaceRes interface {
	deleteFaceRes()
}

type DeleteGuardrailRes interface {
	deleteGuardrailRes()
}

type DeleteObjectivesRes interface {
	deleteObjectivesRes()
}

type DeletePalRes interface {
	deletePalRes()
}

type DeleteToolRes interface {
	deleteToolRes()
}

type DeleteVideoRes interface {
	deleteVideoRes()
}

type EndConversationRes interface {
	endConversationRes()
}

type GetConversationRes interface {
	getConversationRes()
}

type GetDeploymentRes interface {
	getDeploymentRes()
}

type GetDocumentRes interface {
	getDocumentRes()
}

type GetFaceRes interface {
	getFaceRes()
}

type GetGuardrailRes interface {
	getGuardrailRes()
}

type GetObjectivesRes interface {
	getObjectivesRes()
}

type GetPalRes interface {
	getPalRes()
}

type GetToolRes interface {
	getToolRes()
}

type GetVideoRes interface {
	getVideoRes()
}

type ListConversationsRes interface {
	listConversationsRes()
}

type ListDeploymentsRes interface {
	listDeploymentsRes()
}

type ListDocumentsRes interface {
	listDocumentsRes()
}

type ListFacesRes interface {
	listFacesRes()
}

type ListGuardrailsRes interface {
	listGuardrailsRes()
}

type ListObjectivesRes interface {
	listObjectivesRes()
}

type ListPalsRes interface {
	listPalsRes()
}

type ListToolsRes interface {
	listToolsRes()
}

type ListVideosRes interface {
	listVideosRes()
}

type ListVoicesRes interface {
	listVoicesRes()
}

type RenameFaceRes interface {
	renameFaceRes()
}

type RenameVideoRes interface {
	renameVideoRes()
}

type UpdateDeploymentRes interface {
	updateDeploymentRes()
}

type UpdateDocumentRes interface {
	updateDocumentRes()
}

type UpdateGuardrailRes interface {
	updateGuardrailRes()
}

type UpdateObjectivesRes interface {
	updateObjectivesRes()
}

type UpdatePalRes interface {
	updatePalRes()
}

type UpdateToolRes interface {
	updateToolRes()
}
