// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApiKeyAuth handles ApiKeyAuth security.
	// Tavus API key.
	HandleApiKeyAuth(ctx context.Context, operationName OperationName, t ApiKeyAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesApiKeyAuth is a private map storing roles per operation.
var operationRolesApiKeyAuth = map[string][]string{
	AttachToolToPalOperation:    []string{},
	CreateConversationOperation: []string{},
	CreateDeploymentOperation:   []string{},
	CreateDocumentOperation:     []string{},
	CreateFaceOperation:         []string{},
	CreateGuardrailOperation:    []string{},
	CreateObjectivesOperation:   []string{},
	CreatePalOperation:          []string{},
	CreateToolOperation:         []string{},
	CreateVideoOperation:        []string{},
	DeleteConversationOperation: []string{},
	DeleteDeploymentOperation:   []string{},
	DeleteDocumentOperation:     []string{},
	DeleteFaceOperation:         []string{},
	DeleteGuardrailOperation:    []string{},
	DeleteObjectivesOperation:   []string{},
	DeletePalOperation:          []string{},
	DeleteToolOperation:         []string{},
	DeleteVideoOperation:        []string{},
	EndConversationOperation:    []string{},
	GetConversationOperation:    []string{},
	GetDeploymentOperation:      []string{},
	GetDocumentOperation:        []string{},
	GetFaceOperation:            []string{},
	GetGuardrailOperation:       []string{},
	GetObjectivesOperation:      []string{},
	GetPalOperation:             []string{},
	GetToolOperation:            []string{},
	GetVideoOperation:           []string{},
	ListConversationsOperation:  []string{},
	ListDeploymentsOperation:    []string{},
	ListDocumentsOperation:      []string{},
	ListFacesOperation:          []string{},
	ListGuardrailsOperation:     []string{},
	ListObjectivesOperation:     []string{},
	ListPalsOperation:           []string{},
	ListToolsOperation:          []string{},
	ListVideosOperation:         []string{},
	ListVoicesOperation:         []string{},
	RenameFaceOperation:         []string{},
	RenameVideoOperation:        []string{},
	UpdateDeploymentOperation:   []string{},
	UpdateDocumentOperation:     []string{},
	UpdateGuardrailOperation:    []string{},
	UpdateObjectivesOperation:   []string{},
	UpdatePalOperation:          []string{},
	UpdateToolOperation:         []string{},
}

// GetRolesForApiKeyAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyAuth(operation string) []string {
	roles, ok := operationRolesApiKeyAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKeyAuth
	const parameterName = "x-api-key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApiKeyAuth[operationName]
	rctx, err := s.sec.HandleApiKeyAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyAuth provides ApiKeyAuth security value.
	// Tavus API key.
	ApiKeyAuth(ctx context.Context, operationName OperationName) (ApiKeyAuth, error)
}

func (s *Client) securityApiKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyAuth\"")
	}
	req.Header.Set("x-api-key", t.APIKey)
	return nil
}
