// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AttachToolToPal implements attachToolToPal operation.
	//
	// Attaches an existing tool to a PAL. Maximum 50 tools per PAL.
	//
	// POST /v2/pals/{pal_id}/tools
	AttachToolToPal(ctx context.Context, req *AttachToolToPalReq, params AttachToolToPalParams) (AttachToolToPalRes, error)
	// CreateConversation implements createConversation operation.
	//
	// Creates a new real-time conversation session with a PAL.
	// The conversation URL can be used to join the video call.
	//
	// POST /v2/conversations
	CreateConversation(ctx context.Context, req *CreateConversationRequest) (CreateConversationRes, error)
	// CreateDeployment implements createDeployment operation.
	//
	// Creates a distribution channel for a PAL (widget, embed, or landing page).
	//
	// POST /v2/deployments
	CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (CreateDeploymentRes, error)
	// CreateDocument implements createDocument operation.
	//
	// Uploads a document to the knowledge base.
	// Supported formats: PDF, TXT, DOCX, DOC, PNG, JPG, PPTX, CSV, XLSX (max 50MB).
	//
	// POST /v2/documents
	CreateDocument(ctx context.Context, req *CreateDocumentRequest) (CreateDocumentRes, error)
	// CreateFace implements createFace operation.
	//
	// Creates a new face by training on a video or image.
	// Training is asynchronous - use the callback_url or poll the face status.
	//
	// POST /v2/faces
	CreateFace(ctx context.Context, req *CreateFaceRequest) (CreateFaceRes, error)
	// CreateGuardrail implements createGuardrail operation.
	//
	// Creates a behavioral boundary for PAL conversations.
	//
	// POST /v2/guardrails
	CreateGuardrail(ctx context.Context, req *CreateGuardrailRequest) (CreateGuardrailRes, error)
	// CreateObjectives implements createObjectives operation.
	//
	// Creates measurable goals for PAL conversations.
	//
	// POST /v2/objectives
	CreateObjectives(ctx context.Context, req *CreateObjectivesRequest) (CreateObjectivesRes, error)
	// CreatePal implements createPal operation.
	//
	// Creates a new PAL (Personality AI Layer) that defines the avatar's
	// behavior, knowledge, and configuration.
	//
	// POST /v2/pals
	CreatePal(ctx context.Context, req *CreatePalRequest) (CreatePalRes, error)
	// CreateTool implements createTool operation.
	//
	// Creates a function calling tool that can be attached to PALs.
	//
	// POST /v2/tools
	CreateTool(ctx context.Context, req *CreateToolRequest) (CreateToolRes, error)
	// CreateVideo implements createVideo operation.
	//
	// Creates a new video using a face and script or audio.
	// Video generation is asynchronous.
	//
	// POST /v2/videos
	CreateVideo(ctx context.Context, req *CreateVideoRequest) (CreateVideoRes, error)
	// DeleteConversation implements deleteConversation operation.
	//
	// Delete a conversation.
	//
	// DELETE /v2/conversations/{conversation_id}
	DeleteConversation(ctx context.Context, params DeleteConversationParams) (DeleteConversationRes, error)
	// DeleteDeployment implements deleteDeployment operation.
	//
	// Delete a deployment.
	//
	// DELETE /v2/deployments/{deployment_id}
	DeleteDeployment(ctx context.Context, params DeleteDeploymentParams) (DeleteDeploymentRes, error)
	// DeleteDocument implements deleteDocument operation.
	//
	// Delete a document.
	//
	// DELETE /v2/documents/{document_id}
	DeleteDocument(ctx context.Context, params DeleteDocumentParams) (DeleteDocumentRes, error)
	// DeleteFace implements deleteFace operation.
	//
	// Delete a face.
	//
	// DELETE /v2/faces/{face_id}
	DeleteFace(ctx context.Context, params DeleteFaceParams) (DeleteFaceRes, error)
	// DeleteGuardrail implements deleteGuardrail operation.
	//
	// Delete a guardrail.
	//
	// DELETE /v2/guardrails/{guardrail_id}
	DeleteGuardrail(ctx context.Context, params DeleteGuardrailParams) (DeleteGuardrailRes, error)
	// DeleteObjectives implements deleteObjectives operation.
	//
	// Delete objectives.
	//
	// DELETE /v2/objectives/{objectives_id}
	DeleteObjectives(ctx context.Context, params DeleteObjectivesParams) (DeleteObjectivesRes, error)
	// DeletePal implements deletePal operation.
	//
	// Delete a PAL.
	//
	// DELETE /v2/pals/{pal_id}
	DeletePal(ctx context.Context, params DeletePalParams) (DeletePalRes, error)
	// DeleteTool implements deleteTool operation.
	//
	// Delete a tool.
	//
	// DELETE /v2/tools/{tool_id}
	DeleteTool(ctx context.Context, params DeleteToolParams) (DeleteToolRes, error)
	// DeleteVideo implements deleteVideo operation.
	//
	// Delete a video.
	//
	// DELETE /v2/videos/{video_id}
	DeleteVideo(ctx context.Context, params DeleteVideoParams) (DeleteVideoRes, error)
	// EndConversation implements endConversation operation.
	//
	// Gracefully ends an active conversation session.
	//
	// POST /v2/conversations/{conversation_id}/end
	EndConversation(ctx context.Context, params EndConversationParams) (EndConversationRes, error)
	// GetConversation implements getConversation operation.
	//
	// Get a conversation.
	//
	// GET /v2/conversations/{conversation_id}
	GetConversation(ctx context.Context, params GetConversationParams) (GetConversationRes, error)
	// GetDeployment implements getDeployment operation.
	//
	// Get a deployment.
	//
	// GET /v2/deployments/{deployment_id}
	GetDeployment(ctx context.Context, params GetDeploymentParams) (GetDeploymentRes, error)
	// GetDocument implements getDocument operation.
	//
	// Get a document.
	//
	// GET /v2/documents/{document_id}
	GetDocument(ctx context.Context, params GetDocumentParams) (GetDocumentRes, error)
	// GetFace implements getFace operation.
	//
	// Get a face.
	//
	// GET /v2/faces/{face_id}
	GetFace(ctx context.Context, params GetFaceParams) (GetFaceRes, error)
	// GetGuardrail implements getGuardrail operation.
	//
	// Get a guardrail.
	//
	// GET /v2/guardrails/{guardrail_id}
	GetGuardrail(ctx context.Context, params GetGuardrailParams) (GetGuardrailRes, error)
	// GetObjectives implements getObjectives operation.
	//
	// Get objectives.
	//
	// GET /v2/objectives/{objectives_id}
	GetObjectives(ctx context.Context, params GetObjectivesParams) (GetObjectivesRes, error)
	// GetPal implements getPal operation.
	//
	// Get a PAL.
	//
	// GET /v2/pals/{pal_id}
	GetPal(ctx context.Context, params GetPalParams) (GetPalRes, error)
	// GetTool implements getTool operation.
	//
	// Get a tool.
	//
	// GET /v2/tools/{tool_id}
	GetTool(ctx context.Context, params GetToolParams) (GetToolRes, error)
	// GetVideo implements getVideo operation.
	//
	// Get a video.
	//
	// GET /v2/videos/{video_id}
	GetVideo(ctx context.Context, params GetVideoParams) (GetVideoRes, error)
	// ListConversations implements listConversations operation.
	//
	// List all conversations.
	//
	// GET /v2/conversations
	ListConversations(ctx context.Context, params ListConversationsParams) (ListConversationsRes, error)
	// ListDeployments implements listDeployments operation.
	//
	// List all deployments.
	//
	// GET /v2/deployments
	ListDeployments(ctx context.Context, params ListDeploymentsParams) (ListDeploymentsRes, error)
	// ListDocuments implements listDocuments operation.
	//
	// List all documents.
	//
	// GET /v2/documents
	ListDocuments(ctx context.Context, params ListDocumentsParams) (ListDocumentsRes, error)
	// ListFaces implements listFaces operation.
	//
	// List all faces.
	//
	// GET /v2/faces
	ListFaces(ctx context.Context, params ListFacesParams) (ListFacesRes, error)
	// ListGuardrails implements listGuardrails operation.
	//
	// List all guardrails.
	//
	// GET /v2/guardrails
	ListGuardrails(ctx context.Context, params ListGuardrailsParams) (ListGuardrailsRes, error)
	// ListObjectives implements listObjectives operation.
	//
	// List all objectives.
	//
	// GET /v2/objectives
	ListObjectives(ctx context.Context, params ListObjectivesParams) (ListObjectivesRes, error)
	// ListPals implements listPals operation.
	//
	// List all PALs.
	//
	// GET /v2/pals
	ListPals(ctx context.Context, params ListPalsParams) (ListPalsRes, error)
	// ListTools implements listTools operation.
	//
	// List all tools.
	//
	// GET /v2/tools
	ListTools(ctx context.Context, params ListToolsParams) (ListToolsRes, error)
	// ListVideos implements listVideos operation.
	//
	// List all videos.
	//
	// GET /v2/videos
	ListVideos(ctx context.Context, params ListVideosParams) (ListVideosRes, error)
	// ListVoices implements listVoices operation.
	//
	// Lists stock voices available for image-to-face training.
	//
	// GET /v2/voices
	ListVoices(ctx context.Context, params ListVoicesParams) (ListVoicesRes, error)
	// RenameFace implements renameFace operation.
	//
	// Rename a face.
	//
	// PATCH /v2/faces/{face_id}/name
	RenameFace(ctx context.Context, req *RenameFaceReq, params RenameFaceParams) (RenameFaceRes, error)
	// RenameVideo implements renameVideo operation.
	//
	// Rename a video.
	//
	// PATCH /v2/videos/{video_id}/name
	RenameVideo(ctx context.Context, req *RenameVideoReq, params RenameVideoParams) (RenameVideoRes, error)
	// UpdateDeployment implements updateDeployment operation.
	//
	// Update a deployment.
	//
	// PATCH /v2/deployments/{deployment_id}
	UpdateDeployment(ctx context.Context, req *UpdateDeploymentRequest, params UpdateDeploymentParams) (UpdateDeploymentRes, error)
	// UpdateDocument implements updateDocument operation.
	//
	// Update document metadata.
	//
	// PATCH /v2/documents/{document_id}
	UpdateDocument(ctx context.Context, req *UpdateDocumentRequest, params UpdateDocumentParams) (UpdateDocumentRes, error)
	// UpdateGuardrail implements updateGuardrail operation.
	//
	// Update a guardrail.
	//
	// PATCH /v2/guardrails/{guardrail_id}
	UpdateGuardrail(ctx context.Context, req *UpdateGuardrailRequest, params UpdateGuardrailParams) (UpdateGuardrailRes, error)
	// UpdateObjectives implements updateObjectives operation.
	//
	// Update objectives.
	//
	// PATCH /v2/objectives/{objectives_id}
	UpdateObjectives(ctx context.Context, req *UpdateObjectivesRequest, params UpdateObjectivesParams) (UpdateObjectivesRes, error)
	// UpdatePal implements updatePal operation.
	//
	// Update a PAL.
	//
	// PATCH /v2/pals/{pal_id}
	UpdatePal(ctx context.Context, req *UpdatePalRequest, params UpdatePalParams) (UpdatePalRes, error)
	// UpdateTool implements updateTool operation.
	//
	// Update a tool.
	//
	// PATCH /v2/tools/{tool_id}
	UpdateTool(ctx context.Context, req *UpdateToolRequest, params UpdateToolParams) (UpdateToolRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
