// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ConversationProperties) setDefaults() {
	{
		val := int(3600)
		s.MaxCallDuration.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableRecording.SetTo(val)
	}
	{
		val := bool(false)
		s.EnableClosedCaptions.SetTo(val)
	}
	{
		val := bool(false)
		s.ApplyGreenscreen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConversationalFlowLayer) setDefaults() {
	{
		val := bool(true)
		s.TurnTakingEnabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateConversationRequest) setDefaults() {
	{
		val := bool(false)
		s.AudioOnly.SetTo(val)
	}
	{
		val := bool(false)
		s.RequireAuth.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateFaceRequest) setDefaults() {
	{
		val := string("phoenix-4")
		s.ModelName.SetTo(val)
	}
	{
		val := bool(false)
		s.AutoFixTrainingImage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateFaceRequestProperties) setDefaults() {
	{
		val := bool(false)
		s.BackgroundGreenScreen.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateGuardrailRequest) setDefaults() {
	{
		val := CreateGuardrailRequestModality("verbal")
		s.Modality.SetTo(val)
	}
	{
		val := bool(false)
		s.AppMessage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreatePalRequest) setDefaults() {
	{
		val := CreatePalRequestPipelineMode("full")
		s.PipelineMode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateToolRequest) setDefaults() {
	{
		val := CreateToolRequestTriggerType("in_call")
		s.TriggerType.SetTo(val)
	}
	{
		val := CreateToolRequestOrigin("llm")
		s.Origin.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateToolRequestDelivery) setDefaults() {
	{
		val := bool(true)
		s.AppMessage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateVideoRequest) setDefaults() {
	{
		val := bool(false)
		s.Fast.SetTo(val)
	}
	{
		val := bool(false)
		s.TransparentBackground.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateVideoRequestProperties) setDefaults() {
	{
		val := bool(false)
		s.StartWithWave.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ObjectiveItem) setDefaults() {
	{
		val := ObjectiveItemConfirmationMode("auto")
		s.ConfirmationMode.SetTo(val)
	}
	{
		val := ObjectiveItemModality("verbal")
		s.Modality.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PerceptionLayer) setDefaults() {
	{
		val := PerceptionLayerPerceptionModel("off")
		s.PerceptionModel.SetTo(val)
	}
}
