// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AttachToolToPal implements attachToolToPal operation.
//
// Attaches an existing tool to a PAL. Maximum 50 tools per PAL.
//
// POST /v2/pals/{pal_id}/tools
func (UnimplementedHandler) AttachToolToPal(ctx context.Context, req *AttachToolToPalReq, params AttachToolToPalParams) (r AttachToolToPalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateConversation implements createConversation operation.
//
// Creates a new real-time conversation session with a PAL.
// The conversation URL can be used to join the video call.
//
// POST /v2/conversations
func (UnimplementedHandler) CreateConversation(ctx context.Context, req *CreateConversationRequest) (r CreateConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDeployment implements createDeployment operation.
//
// Creates a distribution channel for a PAL (widget, embed, or landing page).
//
// POST /v2/deployments
func (UnimplementedHandler) CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (r CreateDeploymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDocument implements createDocument operation.
//
// Uploads a document to the knowledge base.
// Supported formats: PDF, TXT, DOCX, DOC, PNG, JPG, PPTX, CSV, XLSX (max 50MB).
//
// POST /v2/documents
func (UnimplementedHandler) CreateDocument(ctx context.Context, req *CreateDocumentRequest) (r CreateDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFace implements createFace operation.
//
// Creates a new face by training on a video or image.
// Training is asynchronous - use the callback_url or poll the face status.
//
// POST /v2/faces
func (UnimplementedHandler) CreateFace(ctx context.Context, req *CreateFaceRequest) (r CreateFaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGuardrail implements createGuardrail operation.
//
// Creates a behavioral boundary for PAL conversations.
//
// POST /v2/guardrails
func (UnimplementedHandler) CreateGuardrail(ctx context.Context, req *CreateGuardrailRequest) (r CreateGuardrailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateObjectives implements createObjectives operation.
//
// Creates measurable goals for PAL conversations.
//
// POST /v2/objectives
func (UnimplementedHandler) CreateObjectives(ctx context.Context, req *CreateObjectivesRequest) (r CreateObjectivesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePal implements createPal operation.
//
// Creates a new PAL (Personality AI Layer) that defines the avatar's
// behavior, knowledge, and configuration.
//
// POST /v2/pals
func (UnimplementedHandler) CreatePal(ctx context.Context, req *CreatePalRequest) (r CreatePalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTool implements createTool operation.
//
// Creates a function calling tool that can be attached to PALs.
//
// POST /v2/tools
func (UnimplementedHandler) CreateTool(ctx context.Context, req *CreateToolRequest) (r CreateToolRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateVideo implements createVideo operation.
//
// Creates a new video using a face and script or audio.
// Video generation is asynchronous.
//
// POST /v2/videos
func (UnimplementedHandler) CreateVideo(ctx context.Context, req *CreateVideoRequest) (r CreateVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteConversation implements deleteConversation operation.
//
// Delete a conversation.
//
// DELETE /v2/conversations/{conversation_id}
func (UnimplementedHandler) DeleteConversation(ctx context.Context, params DeleteConversationParams) (r DeleteConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDeployment implements deleteDeployment operation.
//
// Delete a deployment.
//
// DELETE /v2/deployments/{deployment_id}
func (UnimplementedHandler) DeleteDeployment(ctx context.Context, params DeleteDeploymentParams) (r DeleteDeploymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDocument implements deleteDocument operation.
//
// Delete a document.
//
// DELETE /v2/documents/{document_id}
func (UnimplementedHandler) DeleteDocument(ctx context.Context, params DeleteDocumentParams) (r DeleteDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFace implements deleteFace operation.
//
// Delete a face.
//
// DELETE /v2/faces/{face_id}
func (UnimplementedHandler) DeleteFace(ctx context.Context, params DeleteFaceParams) (r DeleteFaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGuardrail implements deleteGuardrail operation.
//
// Delete a guardrail.
//
// DELETE /v2/guardrails/{guardrail_id}
func (UnimplementedHandler) DeleteGuardrail(ctx context.Context, params DeleteGuardrailParams) (r DeleteGuardrailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteObjectives implements deleteObjectives operation.
//
// Delete objectives.
//
// DELETE /v2/objectives/{objectives_id}
func (UnimplementedHandler) DeleteObjectives(ctx context.Context, params DeleteObjectivesParams) (r DeleteObjectivesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePal implements deletePal operation.
//
// Delete a PAL.
//
// DELETE /v2/pals/{pal_id}
func (UnimplementedHandler) DeletePal(ctx context.Context, params DeletePalParams) (r DeletePalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTool implements deleteTool operation.
//
// Delete a tool.
//
// DELETE /v2/tools/{tool_id}
func (UnimplementedHandler) DeleteTool(ctx context.Context, params DeleteToolParams) (r DeleteToolRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteVideo implements deleteVideo operation.
//
// Delete a video.
//
// DELETE /v2/videos/{video_id}
func (UnimplementedHandler) DeleteVideo(ctx context.Context, params DeleteVideoParams) (r DeleteVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EndConversation implements endConversation operation.
//
// Gracefully ends an active conversation session.
//
// POST /v2/conversations/{conversation_id}/end
func (UnimplementedHandler) EndConversation(ctx context.Context, params EndConversationParams) (r EndConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConversation implements getConversation operation.
//
// Get a conversation.
//
// GET /v2/conversations/{conversation_id}
func (UnimplementedHandler) GetConversation(ctx context.Context, params GetConversationParams) (r GetConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeployment implements getDeployment operation.
//
// Get a deployment.
//
// GET /v2/deployments/{deployment_id}
func (UnimplementedHandler) GetDeployment(ctx context.Context, params GetDeploymentParams) (r GetDeploymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocument implements getDocument operation.
//
// Get a document.
//
// GET /v2/documents/{document_id}
func (UnimplementedHandler) GetDocument(ctx context.Context, params GetDocumentParams) (r GetDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFace implements getFace operation.
//
// Get a face.
//
// GET /v2/faces/{face_id}
func (UnimplementedHandler) GetFace(ctx context.Context, params GetFaceParams) (r GetFaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGuardrail implements getGuardrail operation.
//
// Get a guardrail.
//
// GET /v2/guardrails/{guardrail_id}
func (UnimplementedHandler) GetGuardrail(ctx context.Context, params GetGuardrailParams) (r GetGuardrailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetObjectives implements getObjectives operation.
//
// Get objectives.
//
// GET /v2/objectives/{objectives_id}
func (UnimplementedHandler) GetObjectives(ctx context.Context, params GetObjectivesParams) (r GetObjectivesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPal implements getPal operation.
//
// Get a PAL.
//
// GET /v2/pals/{pal_id}
func (UnimplementedHandler) GetPal(ctx context.Context, params GetPalParams) (r GetPalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTool implements getTool operation.
//
// Get a tool.
//
// GET /v2/tools/{tool_id}
func (UnimplementedHandler) GetTool(ctx context.Context, params GetToolParams) (r GetToolRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVideo implements getVideo operation.
//
// Get a video.
//
// GET /v2/videos/{video_id}
func (UnimplementedHandler) GetVideo(ctx context.Context, params GetVideoParams) (r GetVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConversations implements listConversations operation.
//
// List all conversations.
//
// GET /v2/conversations
func (UnimplementedHandler) ListConversations(ctx context.Context, params ListConversationsParams) (r ListConversationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeployments implements listDeployments operation.
//
// List all deployments.
//
// GET /v2/deployments
func (UnimplementedHandler) ListDeployments(ctx context.Context, params ListDeploymentsParams) (r ListDeploymentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDocuments implements listDocuments operation.
//
// List all documents.
//
// GET /v2/documents
func (UnimplementedHandler) ListDocuments(ctx context.Context, params ListDocumentsParams) (r ListDocumentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFaces implements listFaces operation.
//
// List all faces.
//
// GET /v2/faces
func (UnimplementedHandler) ListFaces(ctx context.Context, params ListFacesParams) (r ListFacesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGuardrails implements listGuardrails operation.
//
// List all guardrails.
//
// GET /v2/guardrails
func (UnimplementedHandler) ListGuardrails(ctx context.Context, params ListGuardrailsParams) (r ListGuardrailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListObjectives implements listObjectives operation.
//
// List all objectives.
//
// GET /v2/objectives
func (UnimplementedHandler) ListObjectives(ctx context.Context, params ListObjectivesParams) (r ListObjectivesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPals implements listPals operation.
//
// List all PALs.
//
// GET /v2/pals
func (UnimplementedHandler) ListPals(ctx context.Context, params ListPalsParams) (r ListPalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTools implements listTools operation.
//
// List all tools.
//
// GET /v2/tools
func (UnimplementedHandler) ListTools(ctx context.Context, params ListToolsParams) (r ListToolsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVideos implements listVideos operation.
//
// List all videos.
//
// GET /v2/videos
func (UnimplementedHandler) ListVideos(ctx context.Context, params ListVideosParams) (r ListVideosRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListVoices implements listVoices operation.
//
// Lists stock voices available for image-to-face training.
//
// GET /v2/voices
func (UnimplementedHandler) ListVoices(ctx context.Context, params ListVoicesParams) (r ListVoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameFace implements renameFace operation.
//
// Rename a face.
//
// PATCH /v2/faces/{face_id}/name
func (UnimplementedHandler) RenameFace(ctx context.Context, req *RenameFaceReq, params RenameFaceParams) (r RenameFaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameVideo implements renameVideo operation.
//
// Rename a video.
//
// PATCH /v2/videos/{video_id}/name
func (UnimplementedHandler) RenameVideo(ctx context.Context, req *RenameVideoReq, params RenameVideoParams) (r RenameVideoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDeployment implements updateDeployment operation.
//
// Update a deployment.
//
// PATCH /v2/deployments/{deployment_id}
func (UnimplementedHandler) UpdateDeployment(ctx context.Context, req *UpdateDeploymentRequest, params UpdateDeploymentParams) (r UpdateDeploymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDocument implements updateDocument operation.
//
// Update document metadata.
//
// PATCH /v2/documents/{document_id}
func (UnimplementedHandler) UpdateDocument(ctx context.Context, req *UpdateDocumentRequest, params UpdateDocumentParams) (r UpdateDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGuardrail implements updateGuardrail operation.
//
// Update a guardrail.
//
// PATCH /v2/guardrails/{guardrail_id}
func (UnimplementedHandler) UpdateGuardrail(ctx context.Context, req *UpdateGuardrailRequest, params UpdateGuardrailParams) (r UpdateGuardrailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateObjectives implements updateObjectives operation.
//
// Update objectives.
//
// PATCH /v2/objectives/{objectives_id}
func (UnimplementedHandler) UpdateObjectives(ctx context.Context, req *UpdateObjectivesRequest, params UpdateObjectivesParams) (r UpdateObjectivesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePal implements updatePal operation.
//
// Update a PAL.
//
// PATCH /v2/pals/{pal_id}
func (UnimplementedHandler) UpdatePal(ctx context.Context, req *UpdatePalRequest, params UpdatePalParams) (r UpdatePalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTool implements updateTool operation.
//
// Update a tool.
//
// PATCH /v2/tools/{tool_id}
func (UnimplementedHandler) UpdateTool(ctx context.Context, req *UpdateToolRequest, params UpdateToolParams) (r UpdateToolRes, _ error) {
	return r, ht.ErrNotImplemented
}
